export const EVENTS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',

  POST_CREATED: 'POST_CREATED',
  POST_DELETED: 'POST_DELETED',

  COMMENT_CREATED: 'COMMENT_CREATED',

  REACTION_ADDED: 'REACTION_ADDED',
  REACTION_REMOVED: 'REACTION_REMOVED',

  CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',

  REPUTATION_UPDATED: 'REPUTATION_UPDATED',
  REPUTATION_LEVEL_CHANGED: 'REPUTATION_LEVEL_CHANGED',

  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED'
};