// =========================
// EVENTOS OFICIALES TECNIRED
// =========================

export const EVENTS = Object.freeze({
  // USERS
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_UPDATED: 'USER_UPDATED',
  USER_SUSPENDED: 'USER_SUSPENDED',

  // POSTS
  POST_CREATED: 'POST_CREATED',
  POST_UPDATED: 'POST_UPDATED',
  POST_DELETED: 'POST_DELETED',
  POST_VALIDATED: 'POST_VALIDATED',

  // COMMENTS
  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENT_UPDATED: 'COMMENT_UPDATED',
  COMMENT_DELETED: 'COMMENT_DELETED',

  // REACTIONS
  REACTION_ADDED: 'REACTION_ADDED',
  REACTION_REMOVED: 'REACTION_REMOVED',

  // CHAT
  CHAT_MESSAGE_SENT: 'CHAT_MESSAGE_SENT',
  CHAT_MESSAGE_READ: 'CHAT_MESSAGE_READ',

  // REPUTATION
  REPUTATION_UPDATED: 'REPUTATION_UPDATED',
  REPUTATION_LEVEL_CHANGED: 'REPUTATION_LEVEL_CHANGED',

  // NOTIFICATIONS
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',

  // SYSTEM
  CACHE_INVALIDATED: 'CACHE_INVALIDATED',
  JOB_EXECUTED: 'JOB_EXECUTED',
});

// =========================
// LISTA VALIDACIÓN
// =========================

export const EVENTS_LIST = Object.freeze(
  Object.values(EVENTS),
);

// =========================
// HELPERS
// =========================

export const isValidEvent = (eventName) =>
  EVENTS_LIST.includes(eventName);